"""empty message

Revision ID: 43dd9d3ed95a
Revises: 75d346bddcd7
Create Date: 2023-06-25 19:39:42.411429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43dd9d3ed95a'
down_revision = '75d346bddcd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyecto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proyecto_id', sa.Integer(), nullable=False))
        batch_op.alter_column('aditional_comments',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=90),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'proyecto', ['proyecto_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=8000),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=8000),
               existing_nullable=False)

    with op.batch_alter_table('muestra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('aditional_comments',
               existing_type=sa.String(length=90),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('proyecto_id')

    op.drop_table('proyecto')
    # ### end Alembic commands ###
