"""empty message

Revision ID: ca03d28e6403
Revises: 43dd9d3ed95a
Create Date: 2023-06-25 19:49:19.030191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca03d28e6403'
down_revision = '43dd9d3ed95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direc', sa.String(length=120), nullable=False))
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyecto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('direc')

    # ### end Alembic commands ###
